import json

ref = json.load(open('it_reference.json'))

# Complete Danish translations dictionary
DA = {
    '2fa_disabled': '2FA deaktiveret med succes',
    'a_driver_has_been_assigned_to_your_order': 'En chauffør er blevet tildelt din ordre',
    'about': 'Om',
    'accept_driver': 'Accepter chauffør',
    'accept_net_30_terms': 'Accepter Net 30-vilkår',
    'accept_net_60_terms': 'Accepter Net 60-vilkår',
    'accepted': 'Accepteret',
    'account': 'Konto',
    'account_created': 'Konto oprettet',
    'account_created_can_sign_in': 'Konto oprettet med succes! Du kan nu logge ind.',
    'account_created_success': 'Konto oprettet med succes!',
    'account_deleted_success': 'Konto slettet med succes',
    'account_holder': 'Kontohaver',
    'account_holder_name': 'Kontohavers navn',
    'account_information': 'Kontooplysninger',
    'account_number': 'Kontonummer',
    'account_number_copied': 'Kontonummer kopieret til udklipsholder',
    'account_number_copied_1': 'Kontonummer kopieret',
    'account_successfully_created_and_logged_in': 'Konto oprettet og logget ind med succes!',
    'account_suspended': 'Konto suspenderet',
    'account_verified': 'Konto verificeret!',
    'achEndingIn': 'ACH •••• {last4}',
    'ach_bank_transfer': 'ACH-bankoverførsel',
    'ach_direct_debit': 'ACH-direkte debitering',
    'ach_payment_instructions': 'ACH-betalingsinstruktioner',
    'ach_transfer': 'ACH-overførsel',
    'action_required': 'Handling påkrævet',
    'add': 'Tilføj',
    'add_a_comment_optional': 'Tilføj en kommentar (valgfrit)',
    'add_a_note_optional': 'Tilføj en note (valgfrit)',
    'add_a_note_optionalnexample_please_take_photos_of_': 'Tilføj en note (valgfrit)...\\nEksempel: Tag venligst billeder af produkterne i kassen',
    'add_a_payment_method_to_get_started': 'Tilføj en betalingsmetode for at komme i gang',
    'add_address': 'Tilføj adresse',
    'add_an_address_in_settings': 'Tilføj en adresse i indstillinger',
    'add_new_address': 'Tilføj ny adresse',
    'add_payment_method': 'Tilføj betalingsmetode',
    'add_to_cart': 'Tilføj til kurv',
    'add_to_cart_1': 'Tilføj til kurv',
    'add_your_first_address_to_get_started': 'Tilføj din første adresse for at komme i gang',
    'added_to_favorites': 'Tilføjet til favoritter',
    'address': 'Adresse',
    'address_actions': 'Adressehandlinger',
    'address_deleted_success': 'Adresse slettet med succes',
    'address_information_not_available': 'Adresseoplysninger ikke tilgængelige',
    'address_not_available': 'Adresse ikke tilgængelig',
    'admin': 'Admin',
    'agricultural_products_on_cultioonn_fruits_vegetabl': 'Landbrugsprodukter på Cultioo:\\n\\n🍎 Frugt og grøntsager\\n🥛 Mejeriprodukter og æg\\n🥩 Kød og pålæg\\n🌾 Korn og bælgfrugter\\n🌿 Urter og krydderier\\n\\nBrug markedspladsen til at søge og købe direkte fra verificerede producenter.',
    'all': 'Alle',
    'all_categories': 'Alle kategorier',
    'all_done': 'Alt er klart! 🎉',
    'all_locations': 'Alle lokationer',
    'all_months': 'Alle måneder',
    'already_have_an_account': 'Har du allerede en konto? ',
    'always_in_stock': 'Altid',
    'always_online': 'Altid online',
    'amount_to_transfer': 'Beløb at overføre',
    'amount_to_transfer_1': 'Beløb at overføre',
    'an_error_occurred': 'Der opstod en fejl',
    'an_error_occurred_during_biometric_test': 'Der opstod en fejl under den biometriske test',
    'an_error_occurred_please_try_again': 'Der opstod en fejl. Prøv venligst igen.',
    'an_error_occurred_while_processing_your_payment': 'Der opstod en fejl under behandlingen af din betaling.',
    'appearance': 'Udseende',
    'apple_maps': 'Apple Maps',
    'apple_pay': 'Apple Pay',
    'approval_request_sent': 'Ordrer gemt og godkendelsesanmodning sendt! 📤',
    'approval_required': 'Godkendelse påkrævet',
    'approval_requirement_disabled': 'Godkendelseskrav deaktiveret',
    'approve': 'Godkend',
    'approved': 'Godkendt ✅',
    'are_you_sure_you_want_to_delete_this_address': 'Er du sikker på, at du vil slette denne adresse?',
    'are_you_sure_you_want_to_disable_twofactor_authent': 'Er du sikker på, at du vil deaktivere to-faktor-godkendelse? Dette vil gøre din konto mindre sikker.',
    'are_you_sure_you_want_to_disable_twofactor_authent_1': 'Er du sikker på, at du vil deaktivere to-faktor-godkendelse? Dette vil reducere sikkerheden på din konto.',
    'are_you_sure_you_want_to_reset_all_settings_to_the': 'Er du sikker på, at du vil nulstille alle indstillinger til standardværdierne?',
    'arkadiy_tatarynskyy': 'Arkadiy Tatarynskyy',
    'ask_driver_to_check_product_temperature': 'Bed chaufføren om at kontrollere produkternes temperatur',
    'ask_driver_to_take_photos': 'Bed chaufføren om at tage billeder',
    'auction_duration': 'Auktionsvarighed',
    'auction_ended': 'Auktion afsluttet',
    'auction_expired': 'Auktion udløbet',
    'auction_reset_locally_you_can_start_a_new_auction': 'Auktion nulstillet lokalt. Du kan starte en ny auktion.',
    'auction_reset_you_can_start_a_new_auction': 'Auktion nulstillet. Du kan starte en ny auktion.',
    'auction_started_drivers_can_now_submit_bids': 'Auktion startet! Chauffører kan nu afgive bud.',
    'authenticate_to_access_your_account': 'Godkend for at få adgang til din konto',
    'authenticate_to_access_your_cultioo_account': 'Godkend for at få adgang til din Cultioo-konto',
    'auto_login_failed': 'Automatisk login mislykkedes. Log venligst ind manuelt.',
    'available': 'Tilgængelig',
    'available_drivers': 'Tilgængelige chauffører',
    'awaiting_payment': 'Afventer betaling',
    'bank_account': 'Bankkonto',
    'bank_account_13_days': 'Bankkonto • 1-3 dage',
    'bank_name_optional': 'Banknavn (valgfrit)',
    'bank_transfer': 'BANKOVERFØRSEL',
    'bic_copied_to_clipboard': 'BIC kopieret til udklipsholder',
    'bio_control': 'Biologisk kontrol',
    'biometric_authentication': 'Biometrisk godkendelse',
    'biometric_authentication_disabled': 'Biometrisk godkendelse deaktiveret',
    'biometric_authentication_enabled': 'Biometrisk godkendelse aktiveret',
    'biometric_authentication_is_not_available_on_this_': 'Biometrisk godkendelse er ikke tilgængelig på denne enhed',
    'biometric_authentication_not_available_or_not_enab': 'Biometrisk godkendelse ikke tilgængelig eller ikke aktiveret',
    'biometric_authentication_requires_updated_app_conf': 'Biometrisk godkendelse kræver en opdateret app-konfiguration',
    'biometric_failed': 'Biometrisk godkendelse mislykkedes',
    'biometric_test_info': 'Vi tester din biometriske godkendelse for at sikre, at den fungerer korrekt.',
    'birth_date': 'Fødselsdato',
    'bitte_fge_zuerst_eine_zahlungsmethode_hinzu': 'Tilføj venligst en betalingsmetode først.',
    'block': 'Bloker',
    'block_user': 'Bloker bruger',
    'blockedTime': 'Blokeret {time}',
    'blocked_users': 'Blokerede brugere',
    'business_email': 'Virksomheds-e-mail',
    'business_information': 'Virksomhedsoplysninger',
    'business_name': 'Virksomhedsnavn',
    'business_payment': 'Virksomhedsbetaling',
    'business_phone': 'Virksomhedstelefon',
    'business_verified_processing_payment_terms': 'Virksomhed verificeret! Behandler betalingsvilkår...',
    'buyer': 'Køber',
    'buyer_pays_shipping': 'Køber betaler fragt',
    'by_continuing_you_agree_to_these_terms': 'Ved at fortsætte accepterer du disse vilkår.',
    'by_status': 'Efter status',
    'cancel': 'Annuller',
    'cancel_order': 'Annuller ordre',
    'cancel_order_1': 'Annullere ordren?',
    'cancelled': 'Annulleret',
    'cannot_unfollow_yourself': 'Du kan ikke stoppe med at følge dig selv',
    'capture_required': 'Registrering påkrævet',
    'card_number': 'Kortnummer',
    'card_options': 'Kortindstillinger',
    'card_payment': 'Kortbetaling',
    'card_sepa_ach_wire_transfer': 'Kort, SEPA, ACH, Bankoverførsel',
    'cardholder_name': 'KORTHOLDERS NAVN',
    'cardholder_name_1': 'Kortholders navn',
    'carriage_and_insurance_paid_seller_pays_freight_an': 'Fragt og forsikring betalt - Sælger betaler fragt og forsikring',
    'carriage_paid_to_seller_pays_freight_to_destinatio': 'Fragt betalt til - Sælger betaler fragt til destination',
    'certificate_fee': 'Certifikatgebyr',
    'change_name_email_phone': 'Skift navn, e-mail, telefon, fødselsdato',
    'change_password': 'Skift adgangskode',
    'changing': 'Ændrer...',
    'chat': 'Chat',
    'chat_deleted_locally': 'Chat slettet lokalt',
    'chat_function_is_currently_not_available': 'Chatfunktionen er i øjeblikket ikke tilgængelig',
    'chat_options': 'Chatindstillinger',
    'chat_permanently_deleted': 'Chat permanent slettet',
    'chat_restored': 'Chat gendannet',
    'checking_payment_statuses': 'Kontrollerer betalingsstatusser',
    'checkout': 'Checkout',
    'choose_a_strong_password_with_at_least_6_character': 'Vælg en stærk adgangskode med mindst 6 tegn',
    'choose_an_action_for_this_pdf_file': 'Vælg en handling for denne PDF-fil',
    'choose_app_currency': 'Vælg visningsvaluta',
    'choose_app_language': 'Vælg appens sprog',
    'choose_auth_method': 'Vælg godkendelsesmetode',
    'choose_how_you_want_to_pay': 'Vælg, hvordan du vil betale',
    'choose_payment': 'Vælg betaling',
    'choose_which_invoice_to_download': 'Vælg, hvilken faktura der skal downloades',
    'city': 'By',
    'cleaning_certificate': 'Rengøringscertifikat',
    'cleaning_required': 'Rengøring påkrævet',
    'clear_all': 'Ryd alt',
    'close': 'Luk',
    'code_copied': 'Kode kopieret!',
    'code_will_autosubmit_when_complete': 'Koden sendes automatisk, når den er udfyldt',
    'communication': 'Kommunikation',
    'compare_offers_to_find_the_best_price': 'Sammenlign tilbud for at finde den bedste pris',
    'complete_address_fields': 'Udfyld alle adressefelter',
    'complete_order': 'Fuldfør ordre',
    'confirm': 'Bekræft',
    'confirm_ach_transfer': 'Bekræft ACH-overførsel',
    'confirm_driver': 'Bekræft chauffør',
    'confirm_driver_selection': 'Bekræft valg af chauffør',
    'confirm_new_password': 'Bekræft ny adgangskode',
    'confirm_password': 'Bekræft adgangskode',
    'confirm_password_is_required': 'Bekræftelse af adgangskode er påkrævet',
    'confirm_sepa_transfer': 'Bekræft SEPA-overførsel',
    'confirm_transfer': 'Bekræft overførsel',
    'confirm_wire_transfer': 'Bekræft bankoverførsel',
    'confirmation_required': 'Bekræftelse påkrævet',
    'confirmed': 'Bekræftet',
    'connected_accounts': 'Forbundne konti',
    'connection_error': 'Forbindelsesfejl under automatisk login',
    'connection_timeout_please_check_your_internet': 'Forbindelsestimeout - kontroller venligst din internetforbindelse',
    'contact_driver': 'Kontakt chauffør',
    'contact_information': 'Kontaktoplysninger',
    'contact_seller': 'Kontakt sælger',
    'continue': 'Fortsæt',
    'continue_shopping': 'Fortsæt med at handle',
    'continue_to_payment': 'Fortsæt til betaling',
    'continue_with_google': 'Fortsæt med Google',
    'cost_and_freight_seller_pays_freight_to_destinatio': 'Omkostning og fragt - Sælger betaler fragt til destinationshavnen',
    'cost_insurance_and_freight_seller_pays_freight_and': 'Omkostning, forsikring og fragt - Sælger betaler fragt og forsikring',
    'could_not_access_downloads_directory': 'Kunne ikke få adgang til download-mappen',
    'could_not_load_image': 'Kunne ikke indlæse billedet',
    'could_not_load_products_from_server_categories_ava': 'Kunne ikke indlæse produkter fra serveren. Kategorier tilgængelige offline.',
    'could_not_open_app_settings_please_enable_storage_': 'Kunne ikke åbne appindstillinger. Aktiver venligst lagringstilladelser manuelt i enhedens indstillinger.',
    'could_not_open_image_in_browser': 'Kunne ikke åbne billedet i browseren',
    'could_not_open_pdf': 'Kunne ikke åbne PDF-filen',
    'could_not_sync_favorites_using_offline_data': 'Kunne ikke synkronisere favoritter. Bruger offline-data.',
    'country': 'Land',
    'country_at': 'Østrig',
    'country_be': 'Belgien',
    'country_bg': 'Bulgarien',
    'country_ca': 'Canada',
    'country_ch': 'Schweiz',
    'country_code': 'Landekode',
    'country_cy': 'Cypern',
    'country_cz': 'Tjekkiet',
    'country_de': 'Tyskland',
    'country_dk': 'Danmark',
    'country_ee': 'Estland',
    'country_es': 'Spanien',
    'country_fi': 'Finland',
    'country_fr': 'Frankrig',
    'country_gb': 'Storbritannien',
    'country_gr': 'Grækenland',
    'country_hr': 'Kroatien',
    'country_hu': 'Ungarn',
    'country_ie': 'Irland',
    'country_it': 'Italien',
    'country_lt': 'Litauen',
    'country_lu': 'Luxembourg',
    'country_lv': 'Letland',
    'country_mt': 'Malta',
    'country_mx': 'Mexico',
    'country_nl': 'Nederlandene',
    'country_no': 'Norge',
    'country_pl': 'Polen',
    'country_pt': 'Portugal',
    'country_ro': 'Rumænien',
    'country_ru': 'Rusland',
    'country_se': 'Sverige',
    'country_si': 'Slovenien',
    'country_sk': 'Slovakiet',
    'country_us': 'USA',
    'create_account': 'Opret konto',
    'create_group': 'Opret gruppe',
    'create_your_cultioo_account_and_get_started': 'Opret din Cultioo-konto og kom i gang.',
    'create_your_first_team': 'Opret dit første team',
    'creating': 'Opretter...',
    'credit_card': 'Kreditkort',
    'credit_debit_card': 'Kredit- og debetkort',
    'credit_limit': 'Kreditgrænse',
    'credit_or_debit_card': 'Kredit- eller debetkort',
    'credit_utilization': 'Kreditforbrug',
    'cultioo_gmbh': 'Cultioo GmbH',
    'cultioo_payment_optionsnn_credit_card_visa_masterc': 'Cultioo betalingsmuligheder:\\n\\n💳 **Kreditkort** (Visa, Mastercard, Amex)\\n🏦 **SEPA-direkte debitering**\\n🏛️ **ACH-overførsel**\\n📄 **Bankoverførsel**\\n\\nAlle betalinger behandles via sikre virtuelle Stripe-konti, der er individuelt tildelt din virksomhed.',
    'cultioo_payments_llc': 'Cultioo Payments LLC',
    'cultioo_supportnn_supportcultioocomn_wwwcultioocom': 'Cultioo Support:\\n\\n📧 **support@cultioo.com**\\n🌐 www.cultioo.com\\n\\nFor komplekse juridiske eller forsikringsmæssige spørgsmål anbefaler jeg at kontakte vores menneskelige supportteam direkte.',
    'currency': 'Valuta',
    'currency_bgn': 'Bulgarsk lev (лв)',
    'currency_cad': 'Canadisk dollar (CA\\$)',
    'currency_chf': 'Schweizerfranc (CHF)',
    'currency_czk': 'Tjekkisk krone (Kč)',
    'currency_dkk': 'Dansk krone (kr)',
    'currency_eur': 'Euro (€)',
    'currency_gbp': 'Britisk pund (£)',
    'currency_huf': 'Ungarsk forint (Ft)',
    'currency_mxn': 'Mexicansk peso (MX\\$)',
    'currency_nok': 'Norsk krone (kr)',
    'currency_pln': 'Polsk zloty (zł)',
    'currency_ron': 'Rumænsk leu (lei)',
    'currency_rub': 'Russisk rubel (₽)',
    'currency_sek': 'Svensk krone (kr)',
    'currency_usd': 'Amerikansk dollar (\\$)',
    'current_password': 'Nuværende adgangskode',
    'current_password_is_incorrect': 'Den nuværende adgangskode er forkert',
    'current_status': 'Aktuel status',
    'custom_duration': 'Tilpasset varighed',
    'cvv': 'CVV',
    'dark_mode': 'Mørk tilstand',
    'date_format': 'Datoformat',
    'days_left': 'Dage tilbage',
    'de89_3704_0044_0532_0130_00': 'DE89 3704 0044 0532 0130 00',
    'deAccountEnding': 'DE** **** **** **{last4}',
    'delete': 'Slet',
    'delete_account': 'Slet konto',
    'delete_account_warning': 'Denne handling kan ikke fortrydes. Din konto og alle tilknyttede data vil blive permanent slettet.',
    'delete_address': 'Slet adresse',
    'delete_card': 'Slet kort',
    'delete_group': 'Slet gruppe',
    'delete_group_1': 'Slette gruppen?',
    'delete_my_account': 'Slet min konto',
    'deleted_chats': 'Slettede chats',
    'deleted_chats_will_appear_here': 'Slettede chats vises her',
    'deleting': 'Sletter...',
    'delivered': 'Leveret',
    'delivered_at_place_seller_delivers_to_named_destin': 'Leveret på stedet - Sælger leverer til den navngivne destination',
    'delivered_at_place_unloaded_seller_delivers_and_un': 'Leveret på stedet losset - Sælger leverer og losser',
    'delivered_duty_paid_seller_pays_all_costs_to_desti': 'Leveret fortoldet - Sælger betaler alle omkostninger til destination',
    'delivery_address': 'Leveringsadresse',
    'delivery_and_billing': 'Leverings- og faktureringsadresser',
    'delivery_information': 'LEVERINGSOPLYSNINGER',
    'delivery_information_1': 'Leveringsoplysninger',
    'delivery_overdue': 'Levering forsinket',
    'delivery_time_unknown': 'Leveringstid ukendt',
    'delivery_today': 'Levering i dag!',
    'delvioo_ensures_that_only_registered_and_officiall': 'Delvioo sikrer, at kun registrerede og officielt verificerede chauffører håndterer din levering. Alle forsendelser er forsikrede. I tilfælde af problemer vil vi straks sætte dig i kontakt med support og give alle nødvendige kontaktoplysninger.',
    'delvioo_express': 'Delvioo Express',
    'description_optional': 'Beskrivelse (valgfrit)',
    'deutsche_bank': 'Deutsche Bank',
    'diese_zahlungsmethode_ist_nicht_mehr_gltignbitte_f': 'Denne betalingsmetode er ikke længere gyldig.\\nTilføj venligst et nyt kort.',
    'disable': 'Deaktiver',
    'disable_2fa': 'Deaktiver 2FA',
    'disabled': 'Deaktiveret',
    'discover_amazing_products_and_follow_interesting_s': 'Opdag fantastiske produkter og følg interessante sælgere for at se dem her!',
    'discover_fresh_products': 'Opdag friske produkter og kom i kontakt med lokale sælgere',
    'distance_unit': 'Afstandsenhed',
    'do_you_want_to_reject_this_purchase_request': 'Vil du afvise denne købsanmodning?',
    'done': 'Færdig',
    'dont_have_an_account': 'Har du ikke en konto? ',
    'download': 'Download',
    'download_invoice': 'Download faktura',
    'downloadedToPath': 'Downloadet til {path}',
    'downloadingFile': 'Downloader {fileName}...',
    'driver': 'Chauffør',
    'driver_auction': 'Chaufførauktion',
    'driver_details_not_found_please_reselect_the_drive': 'Chaufføroplysninger ikke fundet. Vælg venligst chaufføren igen, eller prøv igen.',
    'driver_invoice': 'Chaufførfaktura',
    'driver_location': 'Chaufførens placering',
    'driver_location_not_available': 'Chaufførens placering ikke tilgængelig',
    'driver_must_clean_and_sanitize_the_transport_vehic': 'Chaufføren skal rengøre og desinficere transportkøretøjet før lastning',
    'driver_not_available': 'Chauffør ikke tilgængelig',
    'driver_selected': 'Chauffør valgt',
    'drivers_submit_bids_choose_the_best_offer_and_save': 'Chauffører afgiver bud. Vælg det bedste tilbud og spar.',
    'drivers_will_appear_here_once_they_bid': 'Chauffører vises her, når de afgiver bud',
    'drivers_will_include_cleaning_fee_in_their_bid': 'Chauffører vil inkludere rengøringsgebyr i deres bud',
    'due_date': 'Forfaldsdato',
    'edit': 'Rediger',
    'edit_address': 'Rediger adresse',
    'edit_profile': 'Rediger profil',
    'email': 'E-mail',
    'email_address': 'E-mailadresse',
    'email_is_required': 'E-mail er påkrævet',
    'email_sending_may_fail_in_dev_modenuse_this_code_f': 'E-mail-afsendelse kan mislykkes i udviklingstilstand.\\nBrug denne kode til test.',
    'enable_biometric_login': 'Aktiver biometrisk login',
    'enable_glass_dock_with_blur_effects': 'Aktiver glas-dock med sløringseffekter',
    'enabled': 'Aktiveret',
    'enter_a_new_8digit_code_to_replace_your_current_2f': 'Indtast en ny 8-cifret kode for at erstatte din nuværende 2FA-kode',
    'enter_amount': 'Indtast beløb...',
    'enter_an_8digit_code_that_you_want_to_use_for_2fa_': 'Indtast en 8-cifret kode, som du vil bruge til 2FA-godkendelse',
    'enter_auth_code': 'Indtast din godkendelseskode',
    'enter_city': 'Indtast by',
    'enter_code': 'Indtast 8-cifret kode',
    'enter_country': 'Indtast land',
    'enter_eight_digit_code': 'Indtast den 8-cifrede kode',
    'enter_email_address': 'Indtast din e-mailadresse',
    'enter_house_number': 'Indtast husnummer',
    'enter_minutes': 'Indtast minutter',
    'enter_multiplier': 'Indtast multiplikator...',
    'enter_password_to_confirm': 'Indtast adgangskode for at bekræfte',
    'enter_postal_code': 'Indtast postnummer',
    'enter_quantity': 'Indtast antal...',
    'enter_six_digit_code': 'Indtast den 6-cifrede kode',
    'enter_street_and_city': 'Indtast mindst gade og by',
    'enter_street_name': 'Indtast gadenavn',
    'enter_username_password': 'Indtast brugernavn og adgangskode',
    'enter_your_2fa_code_to_continue': 'Indtast din 2FA-kode for at fortsætte',
    'enter_your_6digit_verification_code': 'Indtast din 6-cifrede verifikationskode',
    'enter_your_8digit_verification_code': 'Indtast din 8-cifrede verifikationskode',
    'enter_your_password': 'Indtast din adgangskode',
    'enter_your_registered_business_name': 'Indtast dit registrerede virksomhedsnavn',
    'errorAcceptingBid': 'Fejl ved accept af bud: {error}',
    'errorBlockingUser': 'Fejl ved blokering af bruger: {error}',
    'errorDeletingAddress': 'Fejl ved sletning af adresse: {error}',
    'errorGeneric': 'Fejl: {error}',
    'errorLoadingAddresses': 'Fejl ved indlæsning af adresser: {error}',
    'errorLoadingFollowedUsers': 'Fejl ved indlæsning af fulgte brugere: Status {statusCode}',
    'errorProcessingShippingPayment': 'Fejl ved behandling af fragtbetaling: {error}',
    'errorSavingOrder': 'Fejl ved lagring af ordre: {error}',
    'errorSelectingAddress': 'Fejl ved valg af adresse: {error}',
    'errorUnblockingUser': 'Fejl ved afblokering af bruger: {error}',
    'error_closing_order': 'Fejl ved lukning af ordre',
    'error_deleting_payment_method': 'Fejl ved sletning af betalingsmetode',
    'error_downloading_invoice': 'Fejl ved download af faktura',
    'error_loading_data': 'Fejl ved indlæsning af data',
    'error_loading_orders': 'Fejl ved indlæsning af ordrer',
    'error_loading_payment_methods': 'Fejl ved indlæsning af betalingsmetoder',
    'error_selecting_image': 'Fejl ved valg af billede',
    'error_selecting_pdf_file': 'Fejl ved valg af PDF-fil',
    'error_sending_message': 'Fejl ved afsendelse af besked',
    'error_starting_auction': 'Fejl ved start af auktion',
    'error_title': 'Fejl',
    'error_updating_default': 'Fejl ved opdatering af standard',
    'error_updating_favorites': 'Fejl ved opdatering af favoritter',
    'error_updating_quantity': 'Fejl ved opdatering af antal',
    'estimated_delivery': 'Estimeret levering',
    'europeanFormatDatePreview': 'Europæisk (dd/MM/åååå) - {preview}',
    'every_1_hour': 'Hver time',
    'every_3_hours': 'Hver 3. time',
    'every_6_hours': 'Hver 6. time',
    'everywhere': 'Overalt',
    'ex_works_seller_makes_goods_available_at_their_pre': 'Ab fabrik - Sælger stiller varerne til rådighed på sine egne lokaler',
    'expiresDate': 'Udløber {month}/{year}',
    'expiry': 'Udløb',
    'expiry_date': 'Udløbsdato',
    'failed': 'Mislykket',
    'failedToDownloadFile': 'Download af fil mislykkedes ({statusCode})',
    'failedToFetchLocation': 'Kunne ikke hente placering: {error}',
    'failedToSendMessage': 'Kunne ikke sende besked: {error}',
    'failedToUpdateProfile': 'Kunne ikke opdatere profil: {error}',
    'failedToUpdateSettingWithError': 'Kunne ikke opdatere indstilling: {error}',
    'failed_to_clear_cart': 'Kunne ikke tømme kurven',
    'failed_to_delete_account': 'Kunne ikke slette kontoen',
    'failed_to_load_blocked_users': 'Kunne ikke indlæse blokerede brugere',
    'failed_to_load_products': 'Kunne ikke indlæse produkter',
    'failed_to_remove_item': 'Kunne ikke fjerne vare',
    'failed_to_send_file': 'Kunne ikke sende fil',
    'failed_to_submit_verification': 'Kunne ikke indsende verifikation',
    'failed_to_unblock_user': 'Kunne ikke afblokere bruger',
    'failed_to_unfollow_user': 'Kunne ikke stoppe med at følge bruger',
    'failed_to_update_notification_settings': 'Kunne ikke opdatere notifikationsindstillinger',
    'failed_to_update_quantity': 'Kunne ikke opdatere antal',
    'failed_to_update_setting': 'Kunne ikke opdatere indstilling',
    'failed_to_verify_biometric_authentication': 'Kunne ikke verificere biometrisk godkendelse',
    'failed_to_verify_business_eligibility': 'Kunne ikke verificere virksomhedsberettigelse',
    'faq_and_support': 'FAQ og support',
    'fast_secure': 'Hurtig og sikker',
    'favorite_products': 'Favoritprodukter',
    'favorites': 'Favoritter',
    'feedback_form_coming_soon': 'Feedbackformular kommer snart',
    'fehler_beim_bezahlen_bitte_versuche_es_erneut': 'Fejl ved betaling. Prøv venligst igen.',
    'fill_all_fields': 'Udfyld alle påkrævede felter',
    'fill_all_payment_fields': 'Udfyld alle betalingsfelter',
    'finance': 'Finans',
    'find_users': 'Find brugere',
    'fingerprint_or_face_id': 'Fingeraftryk eller Face ID',
    'first_name': 'Fornavn',
    'follow': 'Følg',
    'follow_sellers_and_users_to_see_them_here': 'Følg sælgere og brugere for at se dem her',
    'forgot_password': 'Glemt adgangskode?',
    'forgot_password_subtitle': 'Indtast din e-mailadresse, og vi sender dig et link til at nulstille din adgangskode.',
    'free_alongside_ship_seller_delivers_alongside_vess': 'Frit langs skib - Sælger leverer langs skibet',
    'free_carrier_seller_delivers_to_carrier_at_named_p': 'Frit fragtfører - Sælger leverer til fragtfører på det navngivne sted',
    'free_on_board_seller_delivers_goods_on_board_vesse': 'Frit ombord - Sælger leverer varerne ombord på skibet',
    'general_help': 'Generel hjælp',
    'generate_new_2fa_code': 'Generer ny 2FA-kode',
    'generate_new_code': 'Generer ny kode',
    'get_competitive_delivery_offers': 'Få konkurrencedygtige leveringstilbud',
    'get_help': 'Få hjælp og support',
    'get_in_touch_directly': 'Kontakt direkte',
    'google_account': 'Google-konto',
    'google_maps': 'Google Maps',
    'google_pay': 'Google Pay',
    'got_it': 'Forstået',
    'gram': 'Gram',
    'group_deleted_successfully': 'Gruppe slettet med succes',
    'group_name': 'Gruppenavn (f.eks. Virksomhed ApS)',
    'groups': 'Grupper',
    'hello_how_can_i_assist_you_with_your_business_need': 'Hej! Hvordan kan jeg hjælpe dig med dine virksomhedsbehov i dag?',
    'help_center': 'Hjælpecenter',
    'help_center_coming_soon': 'Hjælpecenter kommer snart',
    'hey_cully_greeting': 'Hej! Jeg er Cully, din AI-assistent. Hvordan kan jeg hjælpe dig i dag?',
    'high_price': 'Høj pris',
    'highest_price': 'Højeste pris',
    'history': 'Historik',
    'home': 'Hjem',
    'home_subtitle': 'Opdag friske produkter og kom i kontakt med lokale sælgere',
    'house_number': 'Nr.',
    'house_number_1': 'Husnummer',
    'how_it_works': 'Sådan fungerer det',
    'how_to_sign_in': 'Hvordan vil du logge ind?',
    'how_we_handle_data': 'Sådan håndterer vi dine data',
    'how_would_you_like_to_log_in': 'Hvordan vil du logge ind?',
    'iban': 'IBAN',
    'iban_copied': 'IBAN kopieret til udklipsholder',
    'iban_copied_1': 'IBAN kopieret',
    'iban_not_available': 'IBAN ikke tilgængelig',
    'image_decode_error': 'Billedafkodningsfejl',
    'in_stock': 'På lager',
    'includesOverLimitFee': 'Inkluderer {fee} i gebyr over grænsen',
    'incotermLabel': 'Incoterm: {incoterm}',
    'information': 'Information',
    'ingredients_origin': 'INGREDIENSER OG OPRINDELSE',
    'instant_payment': 'ØJEBLIKKELIG BETALING',
    'instant_payment_processing': 'Øjeblikkelig betalingsbehandling',
    'interface': 'Grænseflade',
    'invalid_code': 'Ugyldig kode',
    'invalid_date': 'Ugyldig dato',
    'invalid_date_format': 'Ugyldigt datoformat',
    'invalid_email_address': 'Ugyldig e-mailadresse',
    'invalid_email_or_password': 'Ugyldig e-mail eller adgangskode',
    'invite_code': 'INVITATIONSKODE',
    'invite_code_1': 'Invitationskode',
    'invoiceDueWithinDays': 'Din faktura forfalder inden for {days} dage. Du modtager en detaljeret faktura via e-mail efter at have afgivet ordren.',
    'invoiceSavedTo': 'Faktura gemt i: {path}',
    'invoice_for_product_purchase': 'Faktura for produktkøb',
    'invoice_for_shippingdelivery_service': 'Faktura for fragt-/leveringsservice',
    'invoice_managementnn_view_all_invoices_in_your_acc': 'Fakturastyring:\\n\\n• Se alle fakturaer i sektionen **Konto → Fakturaer**\\n• Betalingsfrister er tydeligt angivet (Net 30 eller Net 60)\\n• Forfaldne fakturaer påvirker din tilgængelige kreditgrænse\\n\\n⚠️ Husk: Ubetalte fakturaer efter forfaldsdato medfører en **bøde på 15%**.',
    'invoice_saved_no_app_to_open_pdf_files': 'Faktura gemt. Ingen app til at åbne PDF-filer.',
    'invoice_sent_to_email': 'Faktura sendt til din e-mail',
    'invoice_total': 'Fakturatotal',
    'issues_test': 'Problemtest',
    'item_removed_from_cart': 'Vare fjernet fra kurven!',
    'item_total': 'Varetotal',
    'itemsCount': 'Varer ({count})',
    'john_doe': 'John Doe',
    'join_group': 'Tilslut gruppe',
    'joining': 'Tilslutter...',
    'just_now': 'Lige nu',
    'keep_order': 'Behold ordre',
    'kilogram': 'Kilogram',
    'kilograms_kg': 'Kilogram (kg)',
    'kilometers': 'kilometer',
    'language': 'Sprog',
    'language_de': 'Tysk',
    'language_en': 'Engelsk',
    'language_es': 'Spansk',
    'language_fr': 'Fransk',
    'language_it': 'Italiensk',
    'language_pt': 'Portugisisk',
    'language_ru': 'Russisk',
    'last_login': 'Sidste login',
    'last_name': 'Efternavn',
    'last_seen': 'Sidst set',
    'late_payment_consequences': 'Konsekvenser ved forsinket betaling',
    'lawsuit_filed': 'Retssag anlagt',
    'leave_group': 'Forlad gruppe',
    'leave_group_1': 'Forlade gruppen?',
    'left_group_successfully': 'Du har forladt gruppen med succes',
    'legal_action': 'Retslige skridt',
    'legal_help': 'Juridisk og hjælp',
    'less_than_24_hours_remaining': 'Mindre end 24 timer tilbage',
    'liter': 'Liter',
    'live_location': 'Live-placering',
    'loading_auction': 'Indlæser auktion...',
    'loading_driver_location': 'Indlæser chaufførens placering...',
    'loading_image': 'Indlæser billede...',
    'loading_product_details': 'Indlæser produktdetaljer...',
    'loading_products': 'Indlæser fantastiske produkter...',
    'loading_your_orders': 'Indlæser dine ordrer...',
    'localization': 'Lokalisering',
    'location': 'Placering',
    'location_not_available': 'Placering ikke tilgængelig',
    'location_not_specified': 'Placering ikke angivet',
    'location_private': 'Privat placering',
    'log_out': 'Log ud',
    'log_out_confirm': 'Vil du virkelig logge ud?',
    'login_cancelled': 'Login annulleret - Du er ikke logget ind',
    'login_credentials': 'Loginoplysninger',
    'login_failed': 'Login mislykkedes',
    'logistics_insurancenn_all_cargo_is_fully_insured_d': 'Logistik og forsikring:\\n\\n🚚 Al fragt er **fuldt forsikret** (detaljer iht. AGB)\\n📸 Skader skal rapporteres inden for **24 timer** med fotodokumentation via appen\\n🚛 Chauffører betales inden for **14 dage** efter levering\\n📍 Leveringsmuligheder varierer efter sælger\\n\\nFor specifikke forsikringsgrænser, se venligst vores servicevilkår (AGB).',
    'low_price': 'Lav pris',
    'main_address': 'HOVEDADRESSE',
    'main_address_updated': 'Hovedadresse opdateret med succes',
    'make_admin': 'Gør til admin',
    'make_member': 'Gør til medlem',
    'make_this_your_default_delivery_address': 'Gør denne til din standardleveringsadresse',
    'manage_addresses': 'Administrer adresser',
    'manage_your_payments': 'Administrer dine betalinger',
    'manage_your_teams': 'Administrer dine teams',
    'manual_login': 'Manuel login',
    'map_loading_failed': 'Indlæsning af kort mislykkedes',
    'maximumFilesAllowed': 'Maksimalt {max} filer tilladt',
    'measurement_interval': 'Måleinterval',
    'member': 'Medlem',
    'member_removed_successfully': 'Medlem fjernet med succes',
    'member_since': 'Medlem siden',
    'members_need_your_approval_before_ordering': 'Medlemmer skal have din godkendelse, før de bestiller',
    'message': 'Besked',
    'message_cully': 'Skriv til Cully',
    'message_options': 'Beskedindstillinger',
    'messages': 'Beskeder',
    'miles': 'miles',
    'milligram': 'Milligram',
    'milliliter': 'Milliliter',
    'modify_address_details': 'Ændr adressedetaljer',
    'money_will_be_transferred_to_sellers_within_2448_h': 'Pengene vil blive overført til sælgerne inden for 24-48 timer.',
    'monthly_statistics': 'Månedlig statistik',
    'motion_dock': 'Motion Dock',
    'motion_dock_disabled': 'Motion dock deaktiveret',
    'motion_dock_enabled': 'Motion dock aktiveret',
    'multiplier_mode': 'Multiplikatortilstand',
    'my_account': 'Min konto',
    'my_addresses': 'Mine adresser',
    'my_orders': 'Mine ordrer',
    'name': 'Navn',
    'native_tab_bar_ios_26': 'Nativ fanebjælke (iOS 26)',
    'netPaymentTerms': 'Net {days} betalingsvilkår',
    'net_30': 'Net 30',
    'net_3060_credit': 'Net 30/60-kredit',
    'net_60': 'Net 60',
    'networkError': 'Netværksfejl: {error}',
    'network_error_please_check_your_internet_connectio': 'Netværksfejl. Kontroller venligst din internetforbindelse.',
    'new_password': 'Ny adgangskode',
    'new_password_must_be_different_from_current_passwo': 'Den nye adgangskode skal være anderledes end den nuværende adgangskode',
    'newest_first': 'Nyeste først',
    'no': 'Nej',
    'no_address': 'Ingen adresse',
    'no_address_provided': 'Ingen adresse angivet',
    'no_addresses_available_please_add_one': 'Ingen adresser tilgængelige. Tilføj venligst en.',
    'no_addresses_found': 'Ingen adresser fundet',
    'no_biometric_enrolled': 'Ingen biometriske data registreret på denne enhed',
    'no_blocked_users': 'Ingen blokerede brugere',
    'no_cleaning_verification_needed': 'Ingen rengøringsverifikation nødvendig',
    'no_code': 'Ingen kode',
    'no_conversations': 'Ingen samtaler',
    'no_date': 'Ingen dato',
    'no_deleted_chats': 'Ingen slettede chats',
    'no_driver_was_selected': 'Ingen chauffør blev valgt',
    'no_favorite_products_yet': 'Ingen favoritprodukter endnu',
    'no_favorites_yet': 'Ingen favoritter endnu',
    'no_groups_yet': 'Ingen grupper endnu',
    'no_internet_connection': 'Ingen internetforbindelse',
    'no_messages_yet': 'Ingen beskeder endnu',
    'no_orders': 'Ingen ordrer',
    'no_orders_yet': 'Ingen ordrer endnu',
    'no_payment_methods': 'Ingen betalingsmetoder',
    'no_pending_requests': 'Ingen ventende anmodninger',
    'no_phone_number': 'Intet telefonnummer',
    'no_photo_requests_yet': 'Ingen fotoanmodninger endnu',
    'no_products_available_from_this_seller': 'Ingen produkter tilgængelige fra denne sælger.',
    'no_products_found': 'Ingen produkter fundet',
    'no_products_subtitle': 'Prøv at ændre filtrene eller kom tilbage senere ✨',
    'no_reviews_yet': 'Ingen anmeldelser endnu',
    'no_saved_payment_methods': 'Ingen gemte betalingsmetoder fundet',
    'no_stripe_customer': 'Ingen Stripe-kunde',
    'no_such_paymentmethod': 'Betalingsmetode findes ikke',
    'no_users_found': 'Ingen brugere fundet',
    'not_available': 'Ikke tilgængelig',
    'not_available_1': 'Ikke tilgængelig',
    'not_following_anyone_yet': 'Følger ingen endnu',
    'not_set': 'Ikke indstillet',
    'not_specified': 'Ikke angivet',
    'notificationsDisabledFor': 'Notifikationer deaktiveret for {seller}',
    'notifiedWhenSellerAdds': 'Du vil blive underrettet, når {seller} tilføjer nye produkter',
    'now': 'Nu',
    'number_format': 'Talformat',
    'number_format_de': 'Tysk (1.234,56)',
    'number_format_en': 'Engelsk (1,234.56)',
    'nutrition_facts': 'NÆRINGSINDHOLD',
    'offline': 'Offline',
    'ok': 'OK',
    'online': 'Online',
    'open': 'Åbn',
    'open_settings': 'Åbn indstillinger',
    'optional_cleaning_certificate_available': 'Valgfrit rengøringscertifikat tilgængeligt',
    'or': 'eller',
    'orderIdsCount': 'Ordre-ID\\\'er ({count}):',
    'orderItemsCount': 'Ordrevarer ({count})',
    'order_approval_workflownn1_orders_created_by_team_': 'Ordregodkendelsesflow:\\n\\n1. Ordrer oprettet af teammedlemmer er først **\\"Afventende\\"**\\n2. **Virksomhedsadministratoren (Boss)** skal godkende hver ordre\\n3. Købere har ikke selvstændigt budget uden administratorgodkendelse\\n4. Når den er godkendt, behandles ordren\\n\\nTjek ordresektionen for statusopdateringer.',
    'order_cancelled': 'Ordre annulleret',
    'order_closed_success': 'Ordre lukket med succes',
    'order_closing': 'Ordrelukning',
    'order_details': 'Ordredetaljer',
    'order_has_been_delivered': 'Ordren er blevet leveret',
    'order_history': 'Ordrehistorik',
    'order_id': 'Ordre-ID',
    'order_ids': 'Ordre-ID\\\'er',
    'order_ids_1': 'Ordre-ID\\\'er:',
    'order_placed_success': 'Ordre afgivet med succes!',
    'order_received_success': 'Ordre markeret som modtaget med succes!',
    'order_rejected': 'Ordre afvist',
    'order_summary': 'Ordreoversigt',
    'order_total': 'Ordretotal',
    'order_value': 'Ordreværdi',
    'order_will_be_automatically_cancelled_if_payment_i': 'Ordren annulleres automatisk, hvis betalingen ikke modtages inden fristen.',
    'orders': 'Ordrer',
    'orders_count': 'Antal ordrer',
    'orders_created': 'Ordrer oprettet!',
    'orders_placed_successfully': 'Ordrer afgivet med succes!',
    'orders_updated': 'Ordrer opdateret:',
    'orders_will_appear_here': 'Dine ordrer vises her, efter du har foretaget et køb',
    'our_team_will_review_your_application_and_notify_y': 'Vores team vil gennemgå din ansøgning og underrette dig via e-mail, når den er godkendt.',
    'ounce': 'Ounce',
    'out_of_stock': 'Udsolgt',
    'out_of_stock_1': 'Udsolgt',
    'out_of_stock_2': 'Udsolgt',
    'overlay_test': 'Overlay-test',
    'owner': 'Ejer',
    'ownership_transferred_successfully': 'Ejerskab overført med succes',
    'paid': 'Betalt',
    'password': 'Adgangskode',
    'password_changed_successfully': 'Adgangskode ændret med succes!',
    'password_is_required': 'Adgangskode er påkrævet',
    'password_is_too_weak': 'Adgangskoden er for svag',
    'password_is_too_weak_please_choose_a_stronger_pass': 'Adgangskoden er for svag. Vælg venligst en stærkere adgangskode.',
    'password_min_length': 'Adgangskoden skal være mindst 6 tegn',
    'password_must_be_at_least_3_characters_long': 'Adgangskoden skal være mindst 3 tegn lang',
    'password_must_be_at_least_6_characters_long': 'Adgangskoden skal være mindst 6 tegn lang',
    'password_reset_success': 'Adgangskode nulstillet med succes! Du kan nu logge ind.',
    'password_reset_will_be_available_soon': 'Nulstilling af adgangskode vil snart være tilgængelig',
    'passwords_do_not_match': 'Adgangskoderne stemmer ikke overens',
    'payAmount': 'Betal {amount}',
    'payShippingAmount': 'Betal fragt {amount}',
    'pay_now': 'Betal nu',
    'pay_shipping_cost': 'Betal fragtomkostninger',
    'pay_within_30_days_business_only': 'Betal inden for 30 dage • Kun virksomheder',
    'pay_within_30_days_from_invoice_date': 'Betal inden for 30 dage fra fakturadatoen',
    'pay_within_60_days_business_only': 'Betal inden for 60 dage • Kun virksomheder',
    'pay_within_60_days_from_invoice_date': 'Betal inden for 60 dage fra fakturadatoen',
    'payment': 'Betaling',
    'paymentCancelledOrFailed': 'Betaling annulleret eller mislykket: {error}',
    'paymentMethodSelected': 'Betalingsmetode valgt: {title}',
    'payment_deadline_expired': 'Betalingsfrist udløbet',
    'payment_deadline_has_passed_this_order_will_be_clo': 'Betalingsfristen er overskredet. Denne ordre lukkes automatisk.',
    'payment_due': 'Betaling forfalder',
    'payment_failed': 'Betaling mislykkedes',
    'payment_failed_1': 'Betaling mislykkedes',
    'payment_id': 'Betalings-ID',
    'payment_id_copied_to_clipboard': 'Betalings-ID kopieret til udklipsholder',
    'payment_instructions': 'Betalingsinstruktioner',
    'payment_method': 'Betalingsmetode',
    'payment_method_deletion_not_yet_implemented': 'Sletning af betalingsmetode er endnu ikke implementeret',
    'payment_method_saved': 'Betalingsmetode gemt med succes!',
    'payment_methods': 'Betalingsmetoder',
    'payment_received': 'Betaling modtaget ✓',
    'payment_reminder': 'Betalingspåmindelse',
    'payment_required': 'Betaling påkrævet',
    'payment_successful': 'Betaling gennemført',
    'payment_successful_1': 'Betaling gennemført!',
    'payment_successful_order_confirmed': 'Betaling gennemført! Ordre bekræftet.',
    'payment_terms': 'Betalingsvilkår',
    'payment_terms_30_days': 'Betalingsvilkår (30 dage)',
    'payment_terms_60_days': 'Betalingsvilkår (60 dage)',
    'payment_terms_b2b': 'BETALINGSVILKÅR (B2B)',
    'payments_secured_by_stripe': 'Betalinger sikret af Stripe',
    'pdf': 'PDF',
    'pdf_document': 'PDF-dokument',
    'pending': 'Afventende',
    'permanently_delete': 'Slet din konto permanent',
    'personal_information': 'Personlige oplysninger',
    'phone': 'Telefon',
    'phone_number': 'Telefonnummer',
    'phone_number_1': 'Telefonnummer',
    'photo': 'Foto',
    'photoRequestSent': 'Fotoanmodning ({interval}) sendt til chaufføren med succes!',
    'photo_interval': 'Fotointerval',
    'photo_requests': 'Fotoanmodninger',
    'photos_from_driver': 'Fotos fra chauffør',
    'photos_received': 'Fotos modtaget',
    'picked_up': 'Afhentet',
    'pickup_complete': 'Afhentning fuldført',
    'pickup_location': 'AFHENTNINGSSTED',
    'piece': 'Styk',
    'platform_fee_65': 'Platformsgebyr (6,5%)',
    'please_authenticate_to_verify_your_identity': 'Godkend venligst for at verificere din identitet',
    'please_confirm_your_new_password': 'Bekræft venligst din nye adgangskode',
    'please_enable_storage_permissions_and_try_download': 'Aktiver venligst lagringstilladelser, og prøv at downloade igen.',
    'please_enter_a_group_name': 'Indtast venligst et gruppenavn',
    'please_enter_a_message': 'Indtast venligst en besked',
    'please_enter_a_valid_8digit_code': 'Indtast venligst en gyldig 8-cifret kode',
    'please_enter_a_valid_duration_between_5_and_180_mi': 'Indtast venligst en gyldig varighed mellem 5 og 180 minutter',
    'please_enter_an_invite_code': 'Indtast venligst en invitationskode',
    'please_enter_your_business_email': 'Indtast venligst din virksomheds-e-mail',
    'please_enter_your_business_name': 'Indtast venligst dit virksomhedsnavn',
    'please_enter_your_business_phone': 'Indtast venligst din virksomhedstelefon',
    'please_enter_your_city': 'Indtast venligst din by',
    'please_enter_your_country': 'Indtast venligst dit land',
    'please_enter_your_house_number': 'Indtast venligst dit husnummer',
    'please_enter_your_postal_code': 'Indtast venligst dit postnummer',
    'please_enter_your_street_address': 'Indtast venligst din adresse',
    'please_enter_your_street_name': 'Indtast venligst dit gadenavn',
    'please_enter_your_tax_id_ein': 'Indtast venligst dit CVR-nummer / momsnummer',
    'please_fill_in_all_fields': 'Udfyld venligst alle felter',
    'please_fill_in_all_fields_correctly': 'Udfyld venligst alle felter korrekt',
    'please_login_again': 'Log venligst ind igen',
    'please_login_first': 'Log venligst ind først',
    'please_login_to_access_feature': 'Log ind for at få adgang til denne funktion',
    'please_login_to_chat': 'Log ind for at chatte med sælgere',
    'please_login_to_follow': 'Log ind for at følge sælgere',
    'please_login_to_view_cart': 'Log ind for at se din kurv',
    'please_select_a_card': 'Vælg venligst et kort',
    'please_select_a_saved_card': 'Vælg venligst et gemt kort',
    'please_select_a_sepa_payment_method': 'Vælg venligst en SEPA-betalingsmetode',
    'please_select_a_wire_transfer_method': 'Vælg venligst en bankoverførselsmetode',
    'please_select_an_ach_payment_method': 'Vælg venligst en ACH-betalingsmetode',
    'please_select_delivery_address_for_all_items': 'Vælg venligst leveringsadresse for alle varer',
    'please_send_a_wire_transfer_for_the_exact_amount_t': 'Send venligst en bankoverførsel for det nøjagtige beløb til den angivne konto. Din ordre bekræftes automatisk efter modtagelse af betaling (normalt samme eller næste hverdag).',
    'please_send_photos_of_the_products': 'Send venligst fotos af produkterne',
    'please_sign_in': 'Log venligst ind',
    'please_transfer_the_exact_amount_to_the_iban_below': 'Overfør venligst det nøjagtige beløb til nedenstående IBAN. Din ordre bekræftes automatisk efter modtagelse af betaling (normalt inden for 1-2 hverdage).',
    'please_transfer_the_exact_amount_via_ach_to_the_ac': 'Overfør venligst det nøjagtige beløb via ACH til den angivne konto. Din ordre bekræftes automatisk efter modtagelse af betaling (normalt 1-3 hverdage).',
    'please_verify_your_identity_with_your_2fa_code': 'Verificer venligst din identitet med din 2FA-kode',
    'please_wait_while_we_process_your_payment': 'Vent venligst, mens vi behandler din betaling',
    'popup_menu_button': 'Popup-menuknap',
    'position_the_qr_code_within_the_frame_to_complete_': 'Placer QR-koden inden for rammen for at fuldføre afhentningen',
    'postal_code': 'Postnummer',
    'pound': 'Pund',
    'pounds_lbs': 'Pund (lbs)',
    'price': 'Pris',
    'pricePerUnit': 'Pris pr. enhed: {price}',
    'price_1': 'Pris ↑',
    'price_2': 'Pris ↓',
    'privacy_policy': 'Privatlivspolitik',
    'privacy_security': 'Privatliv og sikkerhed',
    'proceed_to_checkout': 'Fortsæt til checkout',
    'proceed_to_checkout_1': 'Fortsæt til checkout',
    'processing': 'Behandler',
    'processing_payment': 'Behandler betaling...',
    'processing_time': 'Behandlingstid',
    'product_details': 'PRODUKTDETALJER',
    'product_info': 'Produktinfo',
    'product_information': 'PRODUKTINFORMATION',
    'product_invoice': 'Produktfaktura',
    'productsCount': 'Produkter ({count})',
    'products_0': 'Produkter (0)',
    'profile': 'Profil',
    'profile_updated_success': 'Profil opdateret med succes',
    'qtyWithCount': 'Antal: {quantity}',
    'quantity': 'Antal',
    'quantity_mode': 'Antaltilstand',
    'quick_and_secure_messaging': 'Hurtig og sikker beskedtjeneste',
    'range_5_180_minutes_3_hours_max': 'Interval: 5 - 180 minutter (maks. 3 timer)',
    'rate_driver': 'Bedøm chauffør',
    'rate_seller': 'Bedøm sælger',
    'rate_your_experience': 'Bedøm din oplevelse',
    'rate_your_trip': 'Bedøm din tur',
    'rating': 'Bedømmelse',
    'ready': 'Klar',
    'ready_for_pickup': 'Klar til afhentning',
    'reason_optional': 'Årsag (valgfrit)',
    'refresh': 'Opdater',
    'refresh_location': 'Opdater placering',
    'registration_failed': 'Registrering mislykkedes',
    'reject': 'Afvis',
    'reject_request': 'Afvis anmodning',
    'rejected': 'Afvist ❌',
    'remove': 'Fjern',
    'remove_from_group': 'Fjern fra gruppe',
    'remove_this_address_permanently': 'Fjern denne adresse permanent',
    'remove_this_payment_method': 'Fjern denne betalingsmetode',
    'removed_from_favorites': 'Fjernet fra favoritter',
    'request_information': 'Anmod om information',
    'request_photos': 'Anmod om fotos',
    'request_temperature': 'Anmod om temperatur',
    'request_timeout_server_took_too_long_to_respond': 'Anmodning timeout - serveren var for lang tid om at svare',
    'require_purchase_approval': 'Kræv købsgodkendelse',
    'require_vehicle_cleaning_before_transport': 'Kræv rengøring af køretøj før transport',
    'required_for_this_delivery': 'Påkrævet for denne levering',
    'resend_code': 'Gensend kode',
    'reset': 'Nulstil',
    'reset_password': 'Nulstil adgangskode',
    'reset_password_subtitle': 'Indtast den 6-cifrede kode, der er sendt til din e-mail, og vælg en ny adgangskode.',
    'reset_settings': 'Nulstil indstillinger',
    'reset_to_defaults': 'Nulstil til standardværdier',
    'resetting': 'Nulstiller...',
    'restore_all_settings_to_default_values': 'Gendan alle indstillinger til standardværdier',
    'retry': 'Prøv igen',
    'review_submitted': 'Anmeldelse indsendt',
    'review_time_2448_hours': 'Gennemgangstid: 24-48 timer',
    'role_updated_to_admin': 'Rolle opdateret til Admin',
    'role_updated_to_member': 'Rolle opdateret til Medlem',
    'routing_number': 'Routingnummer',
    'routing_number_copied': 'Routingnummer kopieret til udklipsholder',
    'routing_number_copied_1': 'Routingnummer kopieret',
    'routing_number_swiftbic': 'Routingnummer (SWIFT/BIC)',
    'same_day_delivery': 'Levering samme dag',
    'same_or_next_business_day': 'Samme eller næste hverdag',
    'save': 'Gem',
    'save_changes': 'Gem ændringer',
    'save_code': 'Gem kode',
    'save_payment_method': 'Gem betalingsmetode',
    'saved_cards': 'GEMTE KORT',
    'saved_payment_methods': 'GEMTE BETALINGSMETODER',
    'saved_payment_methods_1': 'Gemte betalingsmetoder',
    'saving': 'Gemmer...',
    'scan_qr_code': 'Scan QR-kode',
    'search_categories': 'Søg kategorier',
    'search_for_users': 'Søg efter brugere',
    'search_products': 'Søg produkter...',
    'search_users': 'Søg brugere...',
    'secure_payment': 'Sikker betaling',
    'security_verification': 'Sikkerhedsverifikation',
    'segmented_control': 'Segmenteret kontrol',
    'select_a_driver': 'Vælg en chauffør',
    'select_a_payment_method': 'Vælg en betalingsmetode',
    'select_address': 'Vælg adresse',
    'select_birth_date': 'Vælg fødselsdato',
    'select_birthdate': 'Vælg fødselsdato',
    'select_birthdate_1': 'Vælg fødselsdato',
    'select_card': 'Vælg kort',
    'select_country': 'Vælg land',
    'select_country_code': 'Vælg landekode',
    'select_currency': 'Vælg valuta',
    'select_delivery_address': 'Vælg en leveringsadresse for alle varer',
    'select_delivery_address_1': 'Vælg leveringsadresse',
    'select_language': 'Vælg sprog',
    'select_month': 'Vælg måned',
    'select_saved_card': 'Vælg gemt kort',
    'select_unit': 'VÆLG ENHED',
    'seller': 'Sælger',
    'seller_not_available': 'Sælger ikke tilgængelig',
    'seller_pays': 'Sælger betaler',
    'seller_pays_shipping': 'Sælger betaler fragten',
    'seller_profile': 'Sælgerprofil',
    'seller_receives': 'Sælger modtager',
    'send_feedback': 'Send feedback',
    'send_image': 'Send billede',
    'send_message': 'Send besked',
    'send_pdf': 'Send PDF',
    'send_request': 'Send anmodning',
    'send_reset_link': 'Send link',
    'send_the_exact_amount_via_wire_transfer_to_the_acc': 'Send det nøjagtige beløb via bankoverførsel til ovenstående konto. Internationale overførsler tager normalt samme eller næste hverdag. Din ordre bekræftes efter modtagelse af betaling.',
    'send_the_first_message': 'Send den første besked!',
    'send_wire_transfer_to_complete_payment': 'Send bankoverførsel for at fuldføre betalingen',
    'sending': 'Sender...',
    'sepaEndingIn': 'SEPA •••• {last4}',
    'sepa_direct_debit': 'SEPA-direkte debitering',
    'sepa_direct_debit_transfers_are_processed_within_1': 'SEPA-overførsler behandles inden for 1-3 hverdage. Din ordre bekræftes efter modtagelse af betaling.',
    'session_expired': 'Session udløbet. Log venligst ind igen.',
    'set_as_default': 'Indstil som standard',
    'set_as_main': 'Indstil som hoved',
    'set_as_main_address': 'Indstil som hovedadresse',
    'set_as_main_address_1': 'Indstil som hovedadresse',
    'set_default_not_yet_implemented': 'Indstil standard er endnu ikke implementeret',
    'setting_updated_successfully': 'Indstilling opdateret med succes',
    'settings': 'Indstillinger',
    'settings_error': 'Fejl ved opdatering af indstillinger',
    'settings_reset_defaults': 'Indstillinger nulstillet til standardværdier',
    'settings_updated': 'Indstillinger opdateret med succes',
    'setup_2fa': 'Opsæt 2FA',
    'share_your_feedback_about_this_order': 'Del din feedback om denne ordre',
    'share_your_thoughts': 'Del dine tanker',
    'shipped': 'Afsendt',
    'shipped_date': 'Afsendelsesdato',
    'shippingCostAmount': 'Fragtomkostninger: \\${amount}',
    'shipping_cost': 'Fragtomkostninger',
    'shipping_method': 'Fragtmetode',
    'shipping_payment_successful_confirming_driver': 'Fragtbetaling gennemført! Bekræfter chauffør...',
    'shipping_terms': 'Fragtvilkår',
    'shipping_will_be_calculated_and_added_at_final_che': 'Fragt beregnes og tilføjes ved den endelige checkout',
    'shopping_cart': 'Indkøbskurv',
    'show_awaiting_only': 'Vis kun afventende',
    'show_this_code_to_the_driver': 'Vis denne kode til chaufføren',
    'sign_in': 'Log ind',
    'sign_in_failed': 'Login mislykkedes',
    'sign_in_subtitle': 'Log ind på din konto for at fortsætte',
    'sign_in_to_view_orders': 'For at se dine ordrer skal du først logge ind.',
    'sign_in_with_password': 'Log ind med brugernavn og adgangskode',
    'sign_out': 'Log ud',
    'signInFailedWithError': 'Login mislykkedes: {error}',
    'signed_in_success': 'Logget ind med succes!',
    'signed_in_with_google': 'Logget ind med Google med succes!',
    'signing_in': 'Logger ind...',
    'sort_az': 'A → Z',
    'sort_by': 'Sorter efter:',
    'sort_orders': 'Sorter ordrer',
    'sort_za': 'Z → A',
    'standard_delivery_terms': 'Standard leveringsvilkår',
    'standard_shipping': 'Standardfragt',
    'start_a_new_chat_to_get_started': 'Start en ny chat for at komme i gang',
    'start_auction': 'Start auktion',
    'start_following_users_to_see_their_profiles_here': 'Begynd at følge brugere for at se deres profiler her',
    'start_new_auction': 'Start ny auktion',
    'start_typing_to_find_people': 'Begynd at skrive for at finde personer',
    'status_accepted': 'ACCEPTERET',
    'status_awaiting_approval': 'AFVENTER GODKENDELSE',
    'status_awaiting_payment': 'AFVENTER BETALING',
    'status_cancelled': 'ANNULLERET',
    'status_confirmed': 'BEKRÆFTET',
    'status_delivered': 'LEVERET',
    'status_payment_failed': 'BETALING MISLYKKET',
    'status_payment_successful': 'BETALING GENNEMFØRT',
    'status_processing': 'BEHANDLER',
    'status_ready_for_pickup': 'KLAR TIL AFHENTNING',
    'status_refunded': 'REFUNDERET',
    'status_shipped': 'AFSENDT',
    'storage_permission_needed': 'Lagringstilladelse nødvendig',
    'street': 'Gade',
    'stripePaymentError': 'Stripe-betalingsfejl: {statusCode}',
    'submit': 'Indsend',
    'submit_continue': 'Indsend og fortsæt',
    'subtotal': 'Subtotal',
    'success': 'Succes',
    'successfully_joined': 'Tilmeldt med succes! 🎉',
    'successfully_logged_in': 'Logget ind med succes!',
    'support': 'Support',
    'swift_code_copied': 'SWIFT-kode kopieret',
    'swiftbic_code': 'SWIFT/BIC-kode',
    'sync_complete': 'Synkronisering fuldført',
    'sync_failed': 'Synkronisering mislykkedes',
    'sync_with_backend': 'Synkroniser med backend',
    'synchronize_settings_across_devices': 'Synkroniser indstillinger på tværs af enheder',
    'syncing_with_stripe': 'Synkroniserer med Stripe...',
    'system': 'System',
    'system_default': 'Systemstandard',
    'tab_bar': 'Fanebjælke',
    'tap_the_heart_icon_on_products_to_add_them_to_your': 'Tryk på hjerteikonet på produkter for at tilføje dem til dine favoritter',
    'tap_to_call': 'Tryk for at ringe',
    'tap_to_view': 'Tryk for at se',
    'tax_id_ein': 'CVR-nummer / Momsnummer',
    'temperature_recorded': 'Temperatur registreret',
    'temperatureRequestSent': 'Temperaturanmodning ({interval}) sendt til chaufføren med succes!',
    'terms_and_conditions': 'Vilkår og betingelser',
    'terms_conditions': 'Vilkår og betingelser',
    'test_biometric_authentication_for_cultioo': 'Test biometrisk godkendelse for Cultioo',
    'test_now': 'Test nu',
    'testing_api_connection': 'Tester API-forbindelse...',
    'text_size': 'Tekststørrelse',
    'text_size_large': 'Stor',
    'text_size_medium': 'Medium',
    'text_size_small': 'Lille',
    'thank_you_for_your_feedback': 'Tak for din feedback!',
    'the_auction_ended_without_any_driver_being_assigne': 'Auktionen sluttede uden, at nogen chauffør blev tildelt. Du kan starte en ny auktion for at finde tilgængelige chauffører.',
    'the_seller_will_pay_for_the_shipping_costs_accordi': 'Sælgeren betaler fragtomkostningerne i henhold til Incoterm-aftalen.',
    'theDriverHasntSharedLocation': 'Chaufføren har endnu ikke delt sin placering',
    'theme': 'Tema',
    'theme_dark': 'Mørkt',
    'theme_lang_currency': 'Tema, sprog, valuta, tekststørrelse',
    'theme_light': 'Lyst',
    'theme_system': 'Telefonindstillinger',
    'this_action_cannot_be_undone_the_order_will_be_per': 'Denne handling kan ikke fortrydes. Ordren lukkes permanent.',
    'this_email_address_is_already_registered': 'Denne e-mailadresse er allerede registreret',
    'this_order_has_been_cancelled': 'Denne ordre er blevet annulleret.',
    'this_order_has_been_rejected_and_will_not_be_proce': 'Denne ordre er blevet afvist og vil ikke blive behandlet.',
    'this_seller_prefers_to_be_contacted_through_the_pl': 'Denne sælger foretrækker at blive kontaktet via platformens beskedsystem af hensyn til privatliv og sikkerhed.',
    'this_will_be_your_default_delivery_address': 'Dette bliver din standardleveringsadresse',
    'this_will_permanently_delete_the_group_for_all_mem': 'Dette sletter permanent gruppen for alle medlemmer.',
    'thisQrCodeDoesntMatch': 'Denne QR-kode matcher ikke ordren',
    'time_remaining_to_pay': 'Resterende tid til betaling',
    'to_download_files_this_app_needs_permission_to_acc': 'For at downloade filer har denne app brug for tilladelse til at tilgå enhedens lager. Dette giver os mulighed for at gemme filer i download-mappen.',
    'to_view_your_messages_you_need_to_sign_in_first': 'For at se dine beskeder skal du først logge ind.',
    'toUnit': 'Til: {unit}',
    'today': 'I dag',
    'todayAtTime': 'I dag, {time}',
    'ton': 'Ton',
    'total': 'Total',
    'totalWithAmount': 'Total: {amount}',
    'total_amount': 'Samlet beløb',
    'total_checked': 'Total kontrolleret:',
    'total_paid': 'Total betalt',
    'total_spent': 'Total brugt',
    'total_statistics': 'Samlet statistik',
    'touch_sensor_test': 'Rør sensoren eller se på kameraet for at teste biometrisk godkendelse',
    'tracking_information': 'Sporingsoplysninger',
    'tracking_number': 'Sporingsnummer',
    'trade_details': 'HANDELSDETALJER',
    'transfer_funds_to_complete_payment': 'Overfør midler for at fuldføre betalingen',
    'transfer_funds_via_ach_to_complete_your_payment': 'Overfør midler via ACH for at fuldføre din betaling',
    'transfer_ownership': 'Overfør ejerskab',
    'transfer_ownership_1': 'Overføre ejerskabet?',
    'transfer_the_exact_amount_via_ach_to_the_virtual_a': 'Overfør det nøjagtige beløb via ACH til ovenstående virtuelle konto. Behandlingstiden er normalt 1-3 hverdage. Din ordre bekræftes efter modtagelse af betaling.',
    'transfer_to_this_iban': 'Overfør til denne IBAN',
    'transit': 'Under transport',
    'try_a_different_search': 'Prøv en anden søgning',
    'try_again': 'Prøv igen',
    'try_different_search': 'Prøv en anden søgning eller gennemse kategorier',
    'two_factor_auth': 'To-faktor-godkendelse',
    'type_address': 'Skriv adresse...',
    'type_message': 'Skriv en besked...',
    'type_your_message': 'Skriv din besked...',
    'ukFormatDatePreview': 'UK-format (dd-MM-åååå) - {preview}',
    'unblock': 'Afbloker',
    'unblock_user': 'Afbloker bruger',
    'unit': 'Enhed',
    'unit_converter': 'Enhedsomregner',
    'unit_converter_1': 'ENHEDSOMREGNER',
    'unknown_date': 'Ukendt dato',
    'unknown_item': 'Ukendt vare',
    'unknown_product': 'Ukendt produkt',
    'unknown_seller': 'Ukendt sælger',
    'unknown_user': 'Ukendt bruger',
    'update_address': 'Opdater adresse',
    'update_code': 'Opdater kode',
    'update_your_password': 'Opdater din adgangskode',
    'updatedTime': 'Opdateret {time}',
    'use_2fa_code': 'Brug 2FA-kode',
    'use_biometric': 'Brug biometri',
    'use_biometric_authentication': 'Brug biometrisk godkendelse',
    'use_biometric_authentication_1': 'Brug biometrisk godkendelse',
    'use_dark_theme_throughout_the_app': 'Brug mørkt tema i hele appen',
    'use_password': 'Brug adgangskode',
    'use_platform_messaging': 'Brug platformens beskedtjeneste',
    'use_saved_card': 'Brug gemt kort',
    'use_saved_payment_method': 'Brug gemt betalingsmetode',
    'use_this_card_for_future_payments': 'Brug dette kort til fremtidige betalinger',
    'user_blocked': 'Bruger blokeret',
    'username': 'Brugernavn',
    'username_can_only_contain_lowercase_letters_number': 'Brugernavn kan kun indeholde små bogstaver, tal, _ og .',
    'username_is_required': 'Brugernavn er påkrævet',
    'username_lowercase_only': 'Brugernavn skal kun være med små bogstaver',
    'username_must_be_at_least_2_characters_long': 'Brugernavn skal være mindst 2 tegn langt',
    'username_or_email': 'Brugernavn eller e-mail',
    'users_you_block_will_appear_here': 'Brugere, du blokerer, vises her',
    'valid_thru': 'GYLDIG TIL',
    'validate_account': 'Verificer konto',
    'variantNumber': 'Variant {number}',
    'verification_code': 'Verifikationskode',
    'verification_code_resent': 'Verifikationskode gensendt',
    'verification_code_sent': 'Verifikationskode sendt til din e-mail',
    'verification_failed': 'Verifikation mislykkedes',
    'verification_sent_to': 'Vi har sendt en 8-cifret verifikationskode til:',
    'verification_submitted': 'Verifikation indsendt',
    'verified_seller': 'Verificeret sælger',
    'verify': 'Verificer',
    'verify_code': 'Verificer kode',
    'verify_email': 'Verificer e-mail',
    'verify_your_identity_to_enable_biometric_authentic': 'Verificer din identitet for at aktivere biometrisk godkendelse',
    'version_info': 'Cultioo App v1.0.0',
    'view_details': 'Se detaljer',
    'view_previous_photo_requests': 'Se tidligere fotoanmodninger',
    'view_terms_of_service': 'Se vores servicevilkår',
    'view_your_orders': 'Se dine ordrer',
    'virtualAccountError': 'Virtuel kontofejl: {statusCode}',
    'virtual_ach_account': 'Virtuel ACH-konto',
    'visa_mastercard_amex': 'Visa, Mastercard, Amex',
    'waiting_for_ach_payment': 'Venter på ACH-betaling',
    'waiting_for_bank_transfer': 'Venter på bankoverførsel...',
    'waiting_for_drivers': 'Venter på chauffører...',
    'waiting_for_drivers_1': 'Venter på chauffører...',
    'waiting_for_photos': 'Venter på fotos',
    'waiting_for_sepa_payment': 'Venter på SEPA-betaling',
    'waiting_for_temperature': 'Venter på temperatur',
    'waiting_for_wire_transfer': 'Venter på bankoverførsel',
    'warning_title': 'Advarsel',
    'weight_unit': 'Vægtenhed',
    'welcome_back': 'Velkommen tilbage',
    'welcome_back_sign_in_to_continue': 'Velkommen tilbage! Log ind for at fortsætte.',
    'welcome_to_cultioo': 'Velkommen til Cultioo',
    'what_happens_if_payment_is_delayed': 'Hvad sker der, hvis betalingen er forsinket',
    'wire_transfer': 'Bankoverførsel',
    'wire_transfer_for_large_payments_only_processing_m': 'Bankoverførsel kun for store betalinger. Behandling kan tage 1-3 hverdage.',
    'wire_transfer_instructions': 'Instruktioner for bankoverførsel',
    'wire_transfers_are_processed_the_same_or_next_busi': 'Bankoverførsler behandles samme eller næste hverdag. Ideel til store nationale og internationale betalinger.',
    'wireEndingIn': 'Overførsel •••• {last4}',
    'wiseEndingIn': 'Wise •••• {last4}',
    'write_review': 'Skriv anmeldelse',
    'yes': 'Ja',
    'yesterday': 'I går',
    'yesterdayAtTime': 'I går, {time}',
    'yesterdayAtTimeMain': 'I går kl. {time}',
    'you_can_only_be_in_one_group_at_a_time': 'Du kan kun være i én gruppe ad gangen',
    'you_have_blocked_this_user': 'Du har blokeret denne bruger',
    'you_will_be_removed_from_this_group': 'Du vil blive fjernet fra denne gruppe.',
    'you_will_no_longer_have_access_to_this_group': 'Du vil ikke længere have adgang til denne gruppe.',
    'your_account': 'Din konto',
    'your_account_number': 'Dit kontonummer',
    'your_business_verification_request_has_been_submit': 'Din virksomhedsverifikationsanmodning er blevet indsendt med succes.',
    'your_cart_is_empty': 'Din kurv er tom',
    'your_data_is_ssl_encrypted_and_secure': 'Dine data er SSL-krypterede og sikre',
    'your_delivery_vehicle_will_be_professionally_clean': 'Dit leveringskøretøj vil blive professionelt rengjort og certificeret, før varerne lastes. Dette sikrer hygiejnisk overholdelse for fødevaretransport.',
    'your_iban': 'Din IBAN',
    'your_name': 'Dit navn',
    'your_order_has_been_placed_successfully': 'Din ordre er blevet afgivet med succes',
    'your_order_history_will_appear_here_when_you_make_': 'Din ordrehistorik vises her, når du foretager køb.',
    'your_order_will_be_automatically_confirmed_once_pa': 'Din ordre bekræftes automatisk efter modtagelse af betaling (normalt 1-2 hverdage)',
    'your_routing_number': 'Dit routingnummer',
    'your_verification_code': 'Din verifikationskode er:',
    'zahlungsmethode_nicht_gefundennbitte_fge_eine_neue': 'Betalingsmetode ikke fundet.\\nTilføj venligst et nyt kort.',
    'zip_code': 'Postnummer',
}

# Self-check
import json, re
ref = json.load(open('it_reference.json'))
assert len(DA) == 1136, f'Expected 1136, got {len(DA)}'
assert set(DA.keys()) == set(ref.keys()), 'Key mismatch!'
for key in ref:
    ref_ph = set(re.findall(r'\{[^}]+\}', ref[key]))
    da_ph = set(re.findall(r'\{[^}]+\}', DA[key]))
    assert ref_ph == da_ph, f'Placeholder mismatch in {key}: {ref_ph} vs {da_ph}'
print(f'✅ All {len(DA)} entries verified. Keys match, placeholders preserved.')
